use presto2;

DROP TABLE IF EXISTS EMPLOYEE, DEPARTMENT, ROLE;

CREATE TABLE DEPARTMENT (
  ID INTEGER AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(30)
) ENGINE=InnoDB;

CREATE TABLE ROLE (
    ROLE_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(30)
) ENGINE=InnoDB;

CREATE TABLE EMPLOYEE (
  EMP_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
  FK_DEPARTMENT_ID INTEGER NULL,
  firstName VARCHAR(30),
  LAST_NAME VARCHAR(30),
  FOREIGN KEY (FK_DEPARTMENT_ID) REFERENCES DEPARTMENT(ID)
) ENGINE=InnoDB;


CREATE TABLE ROLE_EMPLOYEE (
    FK_ROLE_ID INTEGER,
    FK_EMP_ID INTEGER,
    FOREIGN KEY (FK_ROLE_ID) REFERENCES ROLE(ROLE_ID),
    FOREIGN KEY (FK_EMP_ID) REFERENCES EMPLOYEE(EMP_ID)
) ENGINE=InnoDB;

