use presto2;

DROP TABLE EMPLOYEE IF EXISTS;
DROP TABLE DEPARTMENT IF EXISTS;
DROP TABLE ROLE IF EXISTS;

CREATE TABLE DEPARTMENT (
  ID INTEGER AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(30)
);

CREATE TABLE EMPLOYEE (
  EMP_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
  FK_DEPARTMENT_ID INTEGER NULL,
  firstName VARCHAR(30),
  LAST_NAME VARCHAR(30),
  FOREIGN KEY (FK_DEPARTMENT_ID) REFERENCES Department(ID)
);

CREATE TABLE ROLE (
    ROLE_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(30)
);

CREATE TABLE ROLE_EMPLOYEE (
    FK_ROLE_ID INTEGER,
    FK_EMP_ID INTEGER,
    FOREIGN KEY (FK_ROLE_ID) REFERENCES ROLE(ROLE_ID),
    FOREIGN KEY (FK_EMP_ID) REFERENCES EMPLOYEE(EMP_ID)
);

