use presto2;

DROP TABLE IF EXISTS ROLE_EMPLOYEE, EMPLOYEE, DEPARTMENT, ROLE;

CREATE TABLE DEPARTMENT (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(30)
) ENGINE=InnoDB;

CREATE TABLE ROLE (
    ROLE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(30) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE EMPLOYEE (
  EMP_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  FK_DEPARTMENT_ID BIGINT NULL,
  firstName VARCHAR(30) NOT NULL,
  LAST_NAME VARCHAR(30) NOT NULL,
  phone VARCHAR(30) NULL,
  FOREIGN KEY (FK_DEPARTMENT_ID) REFERENCES DEPARTMENT(ID)
) ENGINE=InnoDB;


CREATE TABLE ROLE_EMPLOYEE (
    FK_ROLE_ID BIGINT,
    FK_EMP_ID BIGINT,
    FOREIGN KEY (FK_ROLE_ID) REFERENCES ROLE(ROLE_ID),
    FOREIGN KEY (FK_EMP_ID) REFERENCES EMPLOYEE(EMP_ID)
) ENGINE=InnoDB;

